// <auto-generated />
namespace Motors.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addrequiredfielduser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addrequiredfielduser));
        
        string IMigrationMetadata.Id
        {
            get { return "201710141614567_add required field user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
